### ISSUE TITLE
Dart-specific comment is parsed for iOS build

### ISSUE THREAD

**Issue by jelemar** [heremaps/gluecodium#1186]
This input:
```
struct SomeSettings {
    distance_in_meters: Double = 150.0
    tilt_in_degrees: Double = 50.0
    bearing_in_degrees: Double? = null

    @Swift(Skip)
    @Dart("withDefaults")
    field constructor()

    @Swift(Skip)
    @Dart(Default)
    @Deprecated("Will be removed in vN.N.N. Please use {@Java the default constructor}{@Dart [sdk.navigation.SomeSettings.withDefaults]}{@Cpp the default constructor} instead.")
    field constructor(distance_in_meters, tilt_in_degrees, bearing_in_degrees)
}

```
reports an error in iOS build:
Failed to resolve documentation reference [sdk.navigation.SomeSettings.withDefaults]

There may be 2 bugs involved:
- Gluecodium is parsing a comment for iOS build even though it is referring to definition that is skipped for swift
- Gluecodium is parsing dart-specific comment for iOS build

**Comment by DanielKamkha** [comment]
Not reproducible. When Swift code is generated in isolation, there is, correctly, no warning or error message about a Dart platform comment. Internal investigation shows that the issue is produced by generating Dart and Swift code in the same generation run. In which case the error shows up correctly, as the link is invalid.

Documentation reference links should refer to elements by their IDL names. Currently, there is no way to do so for field constructors. The solutions is either to refer to it textually, as with other platform-specific doc snippets in the example; or to use a verbatim reference: `\[withDefaults\]`. Note that the back-slash escaping is necessary here, it makes the link verbatim, instead of being processed by Gluecodium.
