### ISSUE TITLE
Classes are sometimes created with incorrect visibility

### ISSUE THREAD

**Issue by hitman-codehq** [heremaps/gluecodium#206]
If you create a property in an interface, and then try to override that property in a class that implements that interface, you can end up with incorrect permissions on the derived class.  This leads to the following error:

MyDerivedClass.java:22: error: getMyProperty() in MyDerivedClass cannot implement getMyProperty() in MyInterface
    native double getMyProperty();
                  ^
  attempting to assign weaker access privileges; was public

I have attached two Lime files that can be used to recreate this problem.

**Comment by hitman-codehq** [comment]
[DerivationExample.zip](https://github.com/heremaps/gluecodium/files/4338574/DerivationExample.zip)

**Comment by DanielKamkha** [comment]
The generated code here attempts to reduce visibility on property accessors due to parent-declared property being redeclared in internal child. The real bug here, though, is lack of validation against property redeclaration. It is redundant, Gluecodium will generated accessors for the child class, there is no need to redeclare them in IDL.
