### ISSUE TITLE
Broken links/references in documentation must be checked

### ISSUE THREAD

**Issue by Hsilgos** [heremaps/gluecodium#273]
Currently in big project references might be outdated very soon. Gluecodium should check the references and fail if they are broken.

**Comment by DanielKamkha** [comment]
Gluecodium validates documentation links and emits validation warnings if the links don't resolve to LIME elements. However, such failure does not immediately mean the link is broken. It can be a web link and there is no way to detect this case with 100% accuracy. Hence only a validation warning instead of a validation error.
