### ISSUE TITLE
About project status

### ISSUE THREAD

**Issue by prsolucoes** [heremaps/gluecodium#478]
Hi,

First, thanks for this great project.

Im using djinni today for my projects and today after search for something to generate for dart i found your project.

1. I want know how stable is it for production.
2. I see that you have support for delegate. This let me from C++ call java/swift/kotlin methods?
3. It has support for kotlin and async methods?
4. In djinni we can create custom yml files to make djinni understand custom objects and pass something like pointers (ex: a pointer of image from opencv to java and vice-versa)
5. In djinni we have support for including other yaml files to make reference from other files to records, enums etc. How it work in GC?

Thanks for the answers.

**Comment by Hsilgos** [comment]
Hi. I used to work with djinni, so some of your questions I may answer.
1. We use Gluecodium for regular releases of our products. For example for our last generation of [HERE SDK](https://developer.here.com/products/here-sdk) (versions 4.x) more than year, so I guess it's quite stable.
2. You may call java/swift/flutter methods from C++ for any instance which was passed to C++ before. AFAIR djinni works with the same restrictions.
3. No Kotlin and no async methods (yet). 
4. Recently such possibility was implemented. It's called [external descriptor](https://github.com/heremaps/gluecodium/blob/master/docs/lime_idl.md#external-descriptor). You can use it to pass types and structs from C++ to java/swift/dart and vice versa in similar way as you did it in djinni with yml files.
5. I'm not sure about your case, but seems that it's supported. You may describe external type in lime file (lime file - file with types description) and refer it in other lime files naturally.

Please remember that there are some restrictions in Flutter (Dart) implementation because of status of Flutter (which is in active development).

Also Gluecodium:
- Supports Swift and Dart.
- Supports constructors in all languages. Generated code looks more natural.
- Supports links in generated documentation (in JavaDoc for example).
- Supports properties (this is most valid for swift).
- Supports classes inheritance
- Many other possibilities to tune your generated code.

**Comment by prsolucoes** [comment]
I have a project called ezored (ezored.com or github.com/ezored/ezored) and i use all enums in one file, all domain classes in other file and on services i refer to this enums and domain classes. It is possible? Maybe i can use this into my project ezored. Other companies use that to generate their C++ SDK.

**Comment by Hsilgos** [comment]
Sounds possible for me. We have separate module with 'core' types and refer to this module in different projects. Looks like you need something similar.
Note: I saw in your description that you require CMake 3.14. Gluecodium may work with this, but it's better to lift CMake up to 3.15
