### ISSUE TITLE
Property getters and functions always return by value in C++

### ISSUE THREAD

**Issue by lorensi** [heremaps/gluecodium#515]
**Problem:**

Property getters and functions always return by value in C++, leading to potential performance issues.

Given the following lime code:
```
class Foo {
    property names: List<String>
}
```
The generated C++ code looks like this:
```
class _GLUECODIUM_CPP_EXPORT Foo {
    virtual ::std::vector< ::std::string > get_names(  ) const = 0;
...
```
In order to get a string in a given index the whole vector must be copied. 

**Possible Solution:**

Introduce a new C++ attribute to tell Gluecodium to return by const ref instead of by value, like this:
```
class Foo {
    @Cpp(ReturnByConstRef)
    property names: List<String>
}
```
The generated C++ code would looks like this:
```
class _GLUECODIUM_CPP_EXPORT Foo {
    virtual const ::std::vector< ::std::string >& get_names(  ) const = 0;
...
```

**Comment by DanielKamkha** [comment]
"ReturnByConstRef" is a mouthful. I'd propose a much more succinct `@Cpp(Ref)`. I firmly believe returning a non-const ref from a public API function in C++ is a wrong thing to do. So assuming the refs we ever return from Gluecodium-generated C++ functions are always "const", taking just "Ref" to mark those should be enough.

**Comment by lorensi** [comment]
Totally agree.

**Comment by Hsilgos** [comment]
C++ must store this value inside class. We already have similar behaviour for Java/Swift/Dart, I mean '@Cache' feature. May be it's possible just to extend it to C++?

**Comment by DanielKamkha** [comment]
> 
> 
> C++ must store this value inside class. We already have similar behaviour for Java/Swift/Dart, I mean '@Cache' feature. May be it's possible just to extend it to C++?

`@Cached` controls specifics of generated bindings. Storing a C++ value somewhere is an implementation detail of manually-written code, outside of Gluecodium's control. These are two quite different things, let's not mix them.

**Comment by DanielKamkha** [comment]
As far as I understand, the main use case for this feature is to be used in classes, not interfaces. I propose we restrict the IDL usage to classes only, at least for the initial implementation. 

The reason is that if we allow this for interfaces, this would mean a lot of additional boilerplate for "call platform code from C++" proxy objects (the value returned by the platform function needs to be stored, as @Hsilgos mentioned above). I would like to avoid adding this boilerplate if it is not going to be used. We can always add it later if additional use cases pop up.
