### ISSUE TITLE
Allow classes to implement multiple interfaces

### ISSUE THREAD

**Issue by ManuelKlahn** [heremaps/gluecodium#872]
It would be beneficial if classes could implement multiple interfaces. Consider a class that implements showing the position of  a user on a map. This class will probably be listener for position updates and also wants to be informed about changes of the map status. So considering that there are two lime interfaces PositionListener and MapStatusListener it would be great if this would be possible:
class PositionIndicator: PositionListener, MapStatusListener {
    // Implementation for both interfaces
    (...)
}
Regarding the question of conflicting interfaces it would be totally fine if they result in a generator error or whatever is the easiest solution.

**Comment by DanielKamkha** [comment]
Current pseudo-RTTI used by the generated code only works because the C++ (raw) pointer stays the same, regardless of whether you treat the C++ object as of the child class or as of the parent class. This invariant is broken for multiple inheritance, as for all parent classes beyond the first the raw pointer will be off-set. 

This offset can be, in theory, calculated at compile time and applied to the raw pointers. However, the generated bindings are based on `std::shared_ptr`, and applying pointer arithmetic to a raw pointer managed by an `std::shared_ptr` results in broken code (most probable symptom being double de-allocations).

To make the generated bindings truly function for multiple inheritance, we need `std::dynamic_pointer_cast` or and equivalent operation. Considering multiple inheritance for listener interfaces to be a minor use case, implementing a fully custom `std::dynamic_pointer_cast` analog looks infeasible.

Therefore, the only viable option for multiple inheritance is to use real C++ RTTI `std::dynamic_pointer_cast`. We can limit its usage to multiple inheritance only, preserving the existing pseudo-RTTI for single inheritance as it is, thus keeping all single-inheritance code functional even if RTTI is disabled on C++ compiler level.

**Comment by DanielKamkha** [comment]
Next iteration of the research indicates that dynamic casts most probably won't help at all. Consider the following C++ code, imitating a simplified version of Gluecodium JNI bindings:
```
#include <memory>

class Listener1 {};
class Listener2 {};
class ChildClass: public Listener1, public Listener2 {};

using OpaquePointer = void*;

std::shared_ptr<ChildClass>
create_child_class() { return std::make_shared<ChildClass>(); }

OpaquePointer
convert_to_jni(const std::shared_ptr<ChildClass>& nobj) {
    return reinterpret_cast<void*>(new std::shared_ptr<ChildClass>(nobj));
}

std::shared_ptr<Listener2>
convert_from_jni(const OpaquePointer& jobj) {
    return *reinterpret_cast<std::shared_ptr<Listener2>*>(jobj);
}

int main()
{
  auto nobj = create_child_class();
  auto jobj = convert_to_jni(nobj);
  // User-code cast to Listener2 on Java side
  auto nonsense = convert_from_jni(jobj);
}
```

**Comment by DanielKamkha** [comment]
The proposed alternative solution (successfully tested in a prototype) is the following:
* add a special kind of an interface `listener interface` that behaves the same as the normal `interface`, except as described below
* only "listener interfaces" can be second+ parents of a class/interface with multiple inheritance
* "diamond" inheritance is not supported
* "listener interfaces" do not provide a guarantee of preserving full type information on language boundary crossing the normal interfaces provide:
  * downcasting (casting from parent type to child type) is not supported
  * upcasting works, but breaks referential equality
* all other interface features work normally

Next steps: discuss this internally; if a decisions is made to proceed in this direction, create separate implementation ticket(s).

**Comment by DanielKamkha** [comment]
Created implementation ticket #1077
