### ISSUE TITLE
Fix issues from flutter analyze

### ISSUE THREAD

**Issue by Hsilgos** [heremaps/gluecodium#895]
`flutter analyze` shows huge amount of issued. 85% of them are `non_constant_identifier_names`. I suspect it doesn't like variable `__lib`
5% are about unused imports. 
Notes should be fixed if possible or ignored during `flutter analyze`

**Comment by DanielKamkha** [comment]
One group of the issues that cannot be addressed is lower_snake_case for parameter names of `fromLambdas()` factory constructor for interfaces. These are named parameters and the constructor is public, so renaming the parameters is a breaking change of the public API.

There is, however, a change planned where this constructor is renamed and the parameters are made positional. That'd be a good opportunity to rename the parameters to lowerCamelCase as well.

**Comment by hitman-codehq** [comment]
There are a few more warnings to be addressed, so I'll add each of them as a separate comment in the following format:

info • Unnecessary cast • lib/src/sdk/my_modules/my_class.dart:387:24 • unnecessary_cast

This happens due to the following code fragment:

MyClass$Impl {
  @override
  bool operator ==(dynamic other) {
    if (identical(this, other)) return true;
    if (other is! MyClass$Impl) return false;
    // This causes the warning.  It is already known that this is a MyClass$Impl so there is no need to cast it here
    return __areEqual((this as MyClass$Impl).handle, other.handle) != 0;
  }
}

**Comment by hitman-codehq** [comment]
info • Unnecessary cast • lib/src/sdk/my_modules/my_class.dart:387:24 • unnecessary_cast

This happens due to the following code fragment:

```
MyClass MyClassFromFfi(Pointer<Void> handle) {
  final instance = __lib.getCachedInstance(handle);
  // This causes the warning.  It is already known that this is a MyClass so there is no need to cast it here
  if (instance != null && instance is MyClass) return instance as MyClass;
  ...
}
```

**Comment by hitman-codehq** [comment]
info • Dead code • lib/src/sdk/my_modules/my_class/my_type.dart:55:3 • dead_code

This happens due to the following code fragment:

```
int sdkMyClassMyTypeToFfi(MyType value) {
  switch (value) {
  case XXX:
    return 0;
  // This causes the warning.  The break isn't reached due to the return
  break;
  case YYY:
    return 1;
  // This causes the warning.  The break isn't reached due to the return
  break;
  default:
    throw StateError("Invalid enum value $value for MyType enum.");
  }
}
```
The same problem occurs in the complimentary generated sdkMyClassMyTypeFromFfi method as well.

**Comment by hitman-codehq** [comment]
info • Unused import: 'package:meta/meta.dart' • lib/src/sdk/my_modules/my_class.dart:20:8 • unused_import

This happens due to the following code fragment:

`import 'package:meta/meta.dart';`

**Comment by hitman-codehq** [comment]
info • The member 'handle' can only be used within instance members of subclasses of 'package:sdk/src/_native_base.dart' • lib/src/sdk/my_modules/my_class:187:62 • invalid_use_of_protected_member

This happens due to the following code fragment:

```
class NativeBase {
  @protected
  Pointer<Void> handle = Pointer<Void>.fromAddress(0);
}
```

Which is defined in the generated _native_base.dart file.

**Comment by hitman-codehq** [comment]
One last one and we're done:
info • 'someItem' is deprecated and shouldn't be used. • lib/src/sdk/my_modules/my_class.dart:126:24 • 
Unfortunately this cannot be fixed due to a catch-22 situation: The method or property is deprecated and thus shouldn't be used.  But it needs to continue to function until it is removed and for this, other pieces of generated code need to access it.  So the best way to avoid these is to output an annotation for each line that would trigger this linter warning:
// ignore: deprecated_member_use_from_same_package
This will prevent the warning from being displayed while ensuring that if the generated code references any other deprecated methods, they will still cause a warning, as desired.

**Comment by DanielKamkha** [comment]
The deprecation suppression fix does not work. The suppression comment is in the wrong place.

**Comment by hitman-codehq** [comment]
It would seem that we also have a new unused_import warning appearing in some generated code with Gluecodium 9.3.3.

import 'dart:collection';

This does not appear in all generated code.  Some investigation has shown that .lime files containing collection types such as List<String> **seem** to result in .dart files being generated that contain this unused import.  This is not 100% proven but is certainly a good starting point.
