### ISSUE TITLE
Suggestion: Consider adding a name property to each generated enum.

### ISSUE THREAD

**Issue by marconasio** [heremaps/gluecodium#998]
Very often enum in use are related to errors that need to be reported via logs or tracking tools.

Could be helpful to allow converting them to strings by default

as a quick example:

```
import 'package:enum_to_string/enum_to_string.dart';
import 'package:mypackage';

enum SomeError {
   easyError,
   trickyError,
}

extension SomeErrorExtension on SomeError {
  String get name => EnumToString.convertToString(this);
}
```

**Comment by DanielKamkha** [comment]
"enum_to_string" is a third-party Dart package. Gluecodium doesn't generate code that depends on any third-party libraries/packages, for any language.

I'm assuming you're using Dart in a Flutter project. Flutter "foundation" library already has the functionality you're asking for: https://api.flutter.dev/flutter/foundation/describeEnum.html

**Comment by marconasio** [comment]
Would you consider something like:

```
extension SomeErrorExtension on SomeError {
    String get name => describeEnum(this);
}
```

**Comment by DanielKamkha** [comment]
No, because Dart code generated by Gluecodium is pure Dart, compilable and runnable without the Flutter framework. And `describeEnum()` is from a Flutter library.

I'd suggest your best approach is to make your voice heard by Dart SDK team instead. There are a lot of people unhappy with the verbose `toString()` of enumerators in Dart SDK already. This is a missing/broken language feature and it needs to be fixed closer to the source. 

Gluecodium's aim is to provide a bridge between Dart and C++. Fixing the shortcomings of the Dart language itself is not in the scope of the project.
